[package]
name = "rmg-geom"
version = "0.1.0"
edition = "2021"
description = "Echo geometry primitives: AABB, transforms, temporal proxies, and broad-phase scaffolding"
license = "Apache-2.0"
repository = "https://github.com/flyingrobots/echo"
readme = "../../README.md"
keywords = ["echo", "geometry", "aabb", "broad-phase"]
categories = ["game-engines", "data-structures"]

[dependencies]
rmg-core = { path = "../rmg-core" }

[dev-dependencies]
