[workspace]
members = [
    "crates/rmg-core",
    "crates/rmg-ffi",
    "crates/rmg-wasm",
    "crates/rmg-cli",
    "crates/rmg-geom"
]
resolver = "2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
