# cargo-deny configuration for Echo workspace

[licenses]
# Explicit allowlist of common permissive licenses used in our deps.
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unlicense",
]

# Disallow copyleft by default; we do not expect GPL-family in the runtime.
copyleft = "deny"

# Treat unknown or missing license as a failure.
unlicensed = "deny"

# Confidence threshold for license text detection (default 0.8)
confidence-threshold = 0.8

[bans]
# Warn on multiple versions, but don't fail CI for now.
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

