[package]
name = "rmg-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.68"
description = "Echo FFI: C ABI for host integrations (Lua/C/etc.)"
license = "Apache-2.0"
repository = "https://github.com/flyingrobots/echo"
readme = "README.md"
keywords = ["echo", "ffi", "ecs", "deterministic"]
categories = ["external-ffi-bindings", "game-engines"]

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
rmg-core = { path = "../rmg-core" }
