[package]
name = "rmg-core"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1"
bytes = "1"
thiserror = "1"

[dev-dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
