[package]
name = "rmg-core"
version = "0.1.0"
edition = "2021"
description = "Echo core: deterministic typed graph rewriting engine"
license = "Apache-2.0"
repository = "https://github.com/flyingrobots/echo"
readme = "README.md"
keywords = ["echo", "ecs", "deterministic", "graph"]
categories = ["game-engines", "data-structures"]
build = "build.rs"

[dependencies]
blake3 = "1"
bytes = "1"
thiserror = "1"
hex = { version = "0.4", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = []
# Optional regression check for PRNG sequences; off by default to avoid
# freezing algorithm choices. Used only in tests guarded with `cfg(feature)`.
golden_prng = []
telemetry = ["serde", "serde_json", "hex"]

[build-dependencies]
blake3 = "1"
