[package]
name = "rmg-wasm"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.1"
description = "Echo WASM: wasm-bindgen bindings for tools and web"
license = "Apache-2.0"
repository = "https://github.com/flyingrobots/echo"
readme = "README.md"
keywords = ["echo", "wasm", "ecs", "deterministic"]
categories = ["wasm", "game-engines"]

[lib]
crate-type = ["cdylib"]

[features]
default = []
console-panic = ["console_error_panic_hook"]

[dependencies]
rmg-core = { workspace = true }
wasm-bindgen = "0.2.104"
js-sys = "0.3.81"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
