[package]
name = "rmg-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rmg-core = { path = "../rmg-core" }
wasm-bindgen = "0.2.95"

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
