name: Docs Rollup Check

on:
  pull_request:

jobs:
  echo-total-up-to-date:
    name: echo-total.md is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate echo-total.md
        run: |
          chmod +x scripts/gen-echo-total.sh
          ./scripts/gen-echo-total.sh
      - name: Fail if echo-total.md changed
        run: |
          set -euo pipefail
          if ! git diff --quiet -- docs/echo-total.md; then
            echo "docs/echo-total.md is out of date. Run scripts/gen-echo-total.sh and commit the result." >&2
            git --no-pager diff -- docs/echo-total.md || true
            exit 1
          fi
