name: Docs Rollup Check

on:
  pull_request:

jobs:
  echo-total-up-to-date:
    name: echo-total.md is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate echo-total.md
        run: |
          chmod +x scripts/gen-echo-total.sh
          ./scripts/gen-echo-total.sh
      - name: Fail if echo-total.md changed
        run: |
          set -euo pipefail
          tmp=$(mktemp -d)
          # Save the committed rollup from HEAD and the just-regenerated one
          git show HEAD:docs/echo-total.md > "$tmp/before.md" || true
          cp docs/echo-total.md "$tmp/after.md"
          # Normalize known non-deterministic headers if they appear in older branches
          # (e.g., lines beginning with 'Generated:').
          sed -E '/^Generated:/d' "$tmp/before.md" > "$tmp/before.norm" || true
          sed -E '/^Generated:/d' "$tmp/after.md"  > "$tmp/after.norm"  || true
          if ! diff -u "$tmp/before.norm" "$tmp/after.norm" >/dev/null; then
            echo "docs/echo-total.md is out of date. Run 'make echo-total' (or scripts/gen-echo-total.sh) and commit the result." >&2
            diff -u "$tmp/before.norm" "$tmp/after.norm" || true
            exit 1
          fi
