name: Docs Rollup Check

on:
  pull_request:

jobs:
  echo-total-up-to-date:
    name: echo-total.md is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate echo-total.md
        run: |
          chmod +x scripts/gen-echo-total.sh
          ./scripts/gen-echo-total.sh
      - name: Fail if echo-total.md changed
        run: |
          set -euo pipefail
          tmp=$(mktemp -d)
          # Save the committed rollup from HEAD and the just-regenerated one
          git show HEAD:docs/echo-total.md > "$tmp/before.md" || true
          cp docs/echo-total.md "$tmp/after.md"
          # Normalize header-only legacy lines: remove only in the header region
          # (from file start up to the first blank line) lines that match
          #   ^\s*[Gg]enerated(\s*(:|at:|by:))?
          # This avoids deleting arbitrary occurrences deeper in the document.
          normalize_header() {
            awk '
              BEGIN { in_header=1 }
              {
                if (in_header) {
                  if ($0 ~ /^[[:space:]]*$/) { in_header=0; print; next }
                  if ($0 ~ /^[[:space:]]*[Gg]enerated([[:space:]]*(:|at:|by:))?/) next; else print
                } else { print }
              }
            ' "$1"
          }
          normalize_header "$tmp/before.md" > "$tmp/before.norm" || true
          normalize_header "$tmp/after.md"  > "$tmp/after.norm"  || true
          if ! diff -u "$tmp/before.norm" "$tmp/after.norm" >/dev/null; then
            echo "::error file=docs/echo-total.md,line=1,col=1::docs/echo-total.md is out of date. Run 'make echo-total' (or scripts/gen-echo-total.sh) and commit the result." >&2
            echo "docs/echo-total.md is out of date. Run 'make echo-total' (or scripts/gen-echo-total.sh) and commit the result." >&2
            diff -u "$tmp/before.norm" "$tmp/after.norm" || true
            exit 1
          fi
