name: Security Audit

on:
  push:
    branches:
      - main
      - "echo/**"
      - "feat/**"
  pull_request:

jobs:
  audit:
    name: Cargo Audit (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
