name: Security Audit

on:
  push:
    branches:
      - main
      - "echo/**"
      - "feat/**"
  pull_request:

jobs:
  audit:
    name: Cargo Audit (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin/cargo-audit
          key: audit-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit >/dev/null; then
            cargo install cargo-audit --locked
          fi
      - name: Run cargo audit
        run: cargo audit --deny warnings
