name: Security Audit

on:
  push:
    branches:
      - main
      - "echo/**"
      - "feat/**"
  pull_request:

jobs:
  audit:
    name: Cargo Audit (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit (latest)
        run: cargo install cargo-audit --locked
      - name: Run cargo audit
        run: cargo audit
